version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'support_db'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: php:8.0-apache
    container_name: php_apache_web
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./simple-ticket-api:/var/www/html/ # Updated path
      - ./simple-ticket-api/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf # Updated path
    command: >
      bash -c "
        docker-php-ext-install pdo pdo_mysql &&
        a2enmod rewrite &&
        apache2-foreground
      "

volumes:
  db_data:
